name = "zyrln-bridge"
main = "worker.js"
compatibility_date = "2026-06-09"

[vars]
ZYRLN_RELAY_KEY = "9oAMkiZeRZac1Dcj7g661DLeiwU/TGOj3rorYxmCkXY="

[[durable_objects.bindings]]
name = "TUNNEL_HUB"
class_name = "TunnelHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TunnelHub"]
